server:
  port: 8080

# DATASOURCE
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/todo-api?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

    hibernate:
        ddl-auto: update

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

